dataset: mnist
output_dir: '.'
x_dim: 28
z_dim: 10
lr: 0.0001
alpha: 10
beta: 1
gamma: 0
g_d_freq: 1
g_units: [64,32]
e_units: [32,64]
dz_units: [10,10,5]
dx_units: [64,32]
save_model: True
sd_x: 0.05
scale: 0.5
sample_size: 20000